# Generated by Django 4.0 on 2022-10-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Auction', '0003_remove_customer_user_remove_seller_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bid',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.PositiveBigIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Household', 'Household'), ('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Cosmetics', 'Cosmetics'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
