# Generated by Django 4.0 on 2022-10-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_item_current_bid_item_duration_item_minimum_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
