# Generated by Django 4.0 on 2022-10-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0005_alter_item_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
