# Generated by Django 4.0 on 2022-11-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Auction', '0007_alter_item_item_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid', models.PositiveIntegerField()),
                ('Status', models.BooleanField()),
                ('Bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.item')),
            ],
        ),
    ]
